#
# Module manifest for module 'psSysInfo'
#
# Generated by: BDS
#
# Generated on: 2/26/2016
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'psSysInfo.psm1'

# Version number of this module.
ModuleVersion = '1.1.0'

# Author of this module
Author = 'Brian Sheaffer'

# Company or vendor of this module
#CompanyName = 'Unspecified'

# Copyright statement for this module
Copyright = 'To the extent within my power and possible under law, the author(s) have dedicated all copyright and related and neighboring rights to the public domain worldwide. This is distributed without any warranty.'

# Description of the functionality provided by this module
Description = 'A collection of (what I consider to be) handy wmi and informational functions. '

# Functions to export from this module
FunctionsToExport = 'Get-*'

# Cmdlets to export from this module
CmdletsToExport = ''

# Variables to export from this module
VariablesToExport = ''

# Aliases to export from this module
AliasesToExport = '*'

# HelpInfo URI of this module
HelpInfoURI = 'https://www.github.com/brsh/psSysInfo'

}